### ISSUE TITLE
Create issues of the routes that needs to be implemented

### ISSUE THREAD

**Issue by muslimomar** [RCDD-202203-TUR-BEW/backend-capstone-turkey-students-store#15]
Check the [system architecture design](https://www.figma.com/file/nh2lweFvDxvgt1HzKSrADO/System-architecture-diagram-(Latest-version)?node-id=145%3A334), and for each endpoint there, create an issue here.

Note: don't create issues for the following endpoints, since they're already created: Google, Facebook, Twitter, /signin, /signout

Steps:

1. Create an issue using the following naming convention `Implement GET /products endpoint`.
2. From the right menu, label it as `feature`.
3. In the issue description add this:

## Tasks:

- Implement `POST /products`.
- Add documentation and unit testing.

**Comment by muslimomar** [comment]
@melekarslan13 is it done?

**Comment by melekarslan13** [comment]
yes it is done
