### ISSUE TITLE
Facebook enable production mode

### ISSUE THREAD

**Issue by muslimomar** [RCDD-202203-TUR-BEW/backend-capstone-turkey-students-store#52]
- add privacy policy endpoint
- enable production mode

**Comment by mohammadibrah** [comment]
hello @muslimomar 
- for privacy policy endpoint I found alternative way to implement the page with this URL:
https://www.privacypolicies.com/live/aa6268bd-ea37-43c6-8ad5-9788234c8a53
- I also enabled production mode, however still have an issue with app URL, it seems that localhost not allowed for production mode, for this I believe that we need to deploy Facebook auth first and modify app keys  in .env
